name: application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./csvtojson
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker file
      run: |
        docker build -t dockerfile .
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEYY }}
        aws-region: {{AWS_DEFAULT_REGION}}
    - name: ECR Login
      run: |
       aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 479906876926.dkr.ecr.us-east-1.amazonaws.com
       docker build -t python .
       docker tag python:latest 479906876926.dkr.ecr.us-east-1.amazonaws.com/python:latest
       docker push 479906876926.dkr.ecr.us-east-1.amazonaws.com/python:latest
